const resources = {
    en: {
        translation: {
            defaultGameName: "Game",
            hostInterface: "Host Interface",
            noGamesStarted: "No Games Started",
            createNewGame: "Click the button below to create a new game.",
            numberOfRounds: "Number of rounds",
            createGame: "Create Game",
            reconnectGame: "Reconnect to existing game",
            quitToLogin: "Quit to login",
            hostToken: "Host Token",
            timeRemaining: "Time Remaining",
            seconds: "seconds",
            startTimer: "Start Timer",
            answeringFor: "Answering for",
            firstButton: "First button",
            correct: "Correct",
            wrong: "Wrong",
            cancel: "Cancel",
            setTopics: "Set Topics",
            endGame: "End Game",
            loading: "Loading...",
            roundNamesPlaceholder: "Enter round names one line per round",
            host: "Host",
            player: "Player",
            startNewGame: "Start New Game",
            joinGame: "Join Game",
            hostNamePlaceholder: "Host Name (optional)",
            hostEmailPlaceholder: "Email",
            numRoundsPlaceholder: "Number of Rounds",
            hostCabinet: "Go to Host Cabinet",
            hostCodePlaceholder: "Host Code",
            goToGameSelection: "Go to Game Selection",
            playerNamePlaceholder: "Player Name",
            gameTokenPlaceholder: "Game Token",
            invalidCredentials: "Invalid credentials",
            hostDefaultName: "Host",
            somethingBroke: "Something broke",
            reconnect: "Reconnect",
            logout: "Logout",
            game: "Game",
            round: "Topic",
            question: "Question",
            attemptingAutoJoin: "Attempting to auto-join",
            errorFetchingData: "Error fetching data",
            playerIdOrNameUnavailable: "Player ID or name is not available",
            messengerNotInitialized: "Messenger is not initialized yet",
            gameStatus: "Game Status",
            gameToken: "Game Token",
        },
    },
    ru: {
        translation: {
            defaultGameName: "Игра",
            hostInterface: "Экран ведущего",
            noGamesStarted: "Игры не начаты",
            createNewGame: "Нажмите кнопку ниже, чтобы создать новую игру.",
            numberOfRounds: "Количество раундов",
            createGame: "Создать игру",
            reconnectGame: "Переподключиться к существующей игре",
            quitToLogin: "Выйти на экран входа",
            hostToken: "Код ведущего",
            timeRemaining: "Оставшееся время",
            seconds: "секунд",
            startTimer: "Запустить таймер",
            answeringFor: "Отвечает за",
            firstButton: "Первая кнопка",
            correct: "Правильно",
            wrong: "Неправильно",
            cancel: "Отмена",
            setTopics: "Задать темы",
            endGame: "Завершить игру",
            loading: "Загрузка...",
            roundNamesPlaceholder: "Введите названия тем по одному в строке",
            host: "Ведущий",
            player: "Игрок",
            startNewGame: "Начать Новую Игру",
            joinGame: "Присоединиться",
            hostNamePlaceholder: "Имя Ведущего (не обязательно)",
            hostEmailPlaceholder: "Email",
            numRoundsPlaceholder: "Количество тем",
            hostCabinet: "Зайти в кабинет ведущего",
            hostCodePlaceholder: "Код ведущего",
            goToGameSelection: "Перейти к выбору игр",
            playerNamePlaceholder: "Имя Игрока",
            gameTokenPlaceholder: "Токен Игры",
            invalidCredentials: "Неверные учетные данные",
            hostDefaultName: "Ведущий",
            somethingBroke: "Что-то пошло не так",
            reconnect: "Переподключиться",
            logout: "Выйти",
            game: "Игра",
            round: "Тема",
            question: "Вопрос",
            attemptingAutoJoin: "Попытка автоматического подключения",
            errorFetchingData: "Ошибка при получении данных",
            playerIdOrNameUnavailable: "ID игрока или имя недоступны",
            messengerNotInitialized: "Мессенджер еще не инициализирован",
            gameStatus: "Статус игры",
            gameToken: "Код игры",
        },
    },
};

export default resources;